package boardgamestore.model;

public enum Category {

    ABSTRACT_STRATEGY, ACTING, ACTION_DEXTERITY, ADVENTURE, BOOK, HORROR, MEMORY,
    CARD_GAME, CHILDRENS_GAME, CITY_BUILDING, CIVIL_WAR, CIVILIZATION, CO_OPERATIVE_PLAY,
    COLLECTIBLE_COMPONENTS, COMIC_BOOK, DICE, ECONOMIC, EDUCATIONAL, ELECTRONIC,
    ENVIRONMENTAL, FANTASY, FARMING, FIGHTING, MAZE, MEDICAL, MEDIEVAL, MURDER,
    SCIENCE_FICTION, TRADING, MUSIC, TERRITORY_BUILDING, NEGOTIATION, PARTY_GAME, HUMOR, MOVIE_TV_RADIO_THEME
}
