package boardgamestore.model;

public enum Mechanism {

    ACTING, ACTION_DRAFTING, ACTION_POINTS, ACTION_QUEUE, ALLIANCES, ADVANTAGE_TOKEN,
    AREA_MOVEMENT, AUCTION_BIDDING, AUCTION_DEXTERITY, AREA_IMPULSE, CARD_DRAFTING, COMMAND_CARDS,
    CAMPAIGN, DICE_ROLLING, KILL_STEAL, MARKET, TRADING, TIME_TRACK, AREA_MAJORITY_INFLUENCE,
    GRID_MOVEMENT, FORCE_COMMITMENT, HEXAGON_GRID, MOVEMENT_POINTS, MOVING_MULTIPLE_UNITS, NARRATIVE_CHOICE,
    RACE, TECH_TREES, VARIABLE_PLAYER_POWERS
}
