package boardgamestore.model;

public enum Mechanism {
    ACTING, ACTION_DRAFTING, ACTION_POINTS, ACTION_QUEUE, ALLIANCES, ADVANTAGE_TOKEN, AREA_MOVEMENT, AUCTION_BIDDING,
    AUCTION_DEXTERITY, AREA_IMPULSE, CARD_DRAFTING, COMMAND_CARDS, CAMPAIGN, DICE_ROLLING, KILL_STEAL, MARKET, TRADING,
    TIME_TRACK
}
